; Public OBS Auto Framing installer. Input is the validated public release staging directory.

#define ExpectedAppVersion "0.2.0"
#define AppName "OBS Auto Framing"
#define PluginName "obs-auto-framing"
#define StableAppId "6E0D52B7-3F4C-4B5F-8F0A-8A1EA8E43E46"

#ifndef StagingRoot
  #error StagingRoot must be provided by scripts/build_installer.ps1
#endif
#ifndef OutputDir
  #error OutputDir must be provided by scripts/build_installer.ps1
#endif
#ifndef OutputBaseFilename
  #error OutputBaseFilename must be provided by scripts/build_installer.ps1
#endif
#ifndef AppVersion
  #error AppVersion must be provided by scripts/build_installer.ps1
#endif
#ifndef ReleaseChannel
  #error ReleaseChannel must be provided by scripts/build_installer.ps1
#endif
#ifndef AppPublisher
  #error AppPublisher must be provided by scripts/build_installer.ps1
#endif
#ifndef PolicyIncludePath
  #error PolicyIncludePath must be generated by scripts/build_installer.ps1
#endif

[Setup]
AppId={{{#StableAppId}}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion} {#ReleaseChannel}
AppPublisher={#AppPublisher}
VersionInfoVersion={#AppVersion}
VersionInfoTextVersion={#AppVersion} {#ReleaseChannel}
VersionInfoProductVersion={#AppVersion}
UninstallDisplayName={#AppName}
UninstallDisplayIcon={app}\obs-plugins\64bit\{#PluginName}.dll
DefaultDirName={code:GetInitialObsRoot}
AppendDefaultDirName=no
UsePreviousAppDir=yes
DisableDirPage=no
DisableProgramGroupPage=yes
OutputDir={#OutputDir}
OutputBaseFilename={#OutputBaseFilename}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
PrivilegesRequiredOverridesAllowed=commandline
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
CloseApplications=no
RestartIfNeededByRun=no
SetupLogging=yes
SetupMutex=OBS-Auto-Framing-Public-Installer-{#StableAppId}
UninstallFilesDir={app}\data\obs-plugins\{#PluginName}\installer

[Messages]
SelectDirDesc=Choose the OBS Studio Windows x64 root
SelectDirLabel3=Select the OBS Studio root that contains bin\64bit\obs64.exe. Standard, custom, portable, and prepared runtime roots are supported.

[Files]
Source: "{#StagingRoot}\obs-plugins\64bit\obs-auto-framing.dll"; DestDir: "{app}\obs-plugins\64bit"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(0)
Source: "{#StagingRoot}\obs-plugins\64bit\onnxruntime.dll"; DestDir: "{app}\obs-plugins\64bit"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(1)
Source: "{#StagingRoot}\data\obs-plugins\obs-auto-framing\effects\crop.effect"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\effects"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(2)
Source: "{#StagingRoot}\data\obs-plugins\obs-auto-framing\locale\en-US.ini"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\locale"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(3)
Source: "{#StagingRoot}\data\obs-plugins\obs-auto-framing\models\yolox_tiny.onnx"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\models"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(4)
Source: "{#StagingRoot}\docs\install.md"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\docs"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(5)
Source: "{#StagingRoot}\docs\troubleshooting.md"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\docs"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(6)
Source: "{#StagingRoot}\LICENSE"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\docs"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(7)
Source: "{#StagingRoot}\README.md"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\docs"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(8)
Source: "{#StagingRoot}\SECURITY.md"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\docs"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(9)
Source: "{#StagingRoot}\THIRD_PARTY_NOTICES.md"; DestDir: "{app}\data\obs-plugins\obs-auto-framing\docs"; Flags: ignoreversion uninsneveruninstall; Check: ShouldInstallPayload(10)

[Code]
#include PolicyIncludePath

const
  PowerShellObsRunningResult = 10;

var
  PayloadWillCopy: array[0..CompiledPayloadCount - 1] of Boolean;
  PayloadExistedBefore: array[0..CompiledPayloadCount - 1] of Boolean;
  PayloadOriginalHash: array[0..CompiledPayloadCount - 1] of String;
  PayloadCreatedByInstaller: array[0..CompiledPayloadCount - 1] of Boolean;

function ManifestPath(): String;
begin
  Result := ExpandConstant(
    '{app}\data\obs-plugins\{#PluginName}\installer\install-manifest.ini');
end;

function ObsRootIsValid(Path: String): Boolean;
begin
  Result := FileExists(AddBackslash(Path) + 'bin\64bit\obs64.exe');
end;

function GetInitialObsRoot(Param: String): String;
var
  StandardRoot: String;
begin
  StandardRoot := ExpandConstant('{commonpf64}\obs-studio');
  if ObsRootIsValid(StandardRoot) then
    Result := StandardRoot
  else
    Result := ExpandConstant('{sd}\');
end;

function QueryObsRunning(var CheckFailed: Boolean): Boolean;
var
  ResultCode: Integer;
  PowerShellPath: String;
  Parameters: String;
begin
  CheckFailed := False;
  PowerShellPath := ExpandConstant('{sys}\WindowsPowerShell\v1.0\powershell.exe');
  Parameters :=
    '-NoProfile -NonInteractive -WindowStyle Hidden -Command ' +
    '"if (Get-Process -Name ''obs64'' -ErrorAction SilentlyContinue) { exit 10 }; exit 0"';
  if not Exec(PowerShellPath, Parameters, '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
  begin
    CheckFailed := True;
    Result := True;
    exit;
  end;
  if ResultCode = PowerShellObsRunningResult then
    Result := True
  else if ResultCode = 0 then
    Result := False
  else
  begin
    CheckFailed := True;
    Result := True;
  end;
end;

function CommandLineIsSilent(): Boolean;
var
  Index: Integer;
begin
  Result := False;
  for Index := 1 to ParamCount() do
    if (CompareText(ParamStr(Index), '/SILENT') = 0) or
       (CompareText(ParamStr(Index), '/VERYSILENT') = 0) then
    begin
      Result := True;
      exit;
    end;
end;

function RefuseIfObsRunning(Silent: Boolean): Boolean;
var
  CheckFailed: Boolean;
begin
  Result := QueryObsRunning(CheckFailed);
  if Result and not Silent then
  begin
    if CheckFailed then
      MsgBox(
        'Setup could not safely determine whether OBS Studio is running.' + #13#10 + #13#10 +
        'Close OBS and verify Windows PowerShell can query processes, then try again.',
        mbCriticalError, MB_OK)
    else
      MsgBox(
        'OBS Studio is running. Close OBS before installing, upgrading, repairing, or uninstalling OBS Auto Framing.',
        mbCriticalError, MB_OK);
  end;
end;

function InitializeSetup(): Boolean;
begin
  Result := not RefuseIfObsRunning(CommandLineIsSilent());
end;

function InitializeUninstall(): Boolean;
begin
  Result := not RefuseIfObsRunning(CommandLineIsSilent());
end;

function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (CurPageID = wpSelectDir) and not ObsRootIsValid(WizardDirValue()) then
  begin
    if not WizardSilent() then
      MsgBox(
        'This is not a valid OBS Studio Windows x64 root.' + #13#10 + #13#10 +
        'Select the folder that contains bin\64bit\obs64.exe. No files have been written.',
        mbCriticalError, MB_OK);
    Result := WizardSilent();
  end;
end;

function ShouldInstallPayload(Index: Integer): Boolean;
begin
  Result := PayloadWillCopy[Index];
end;

function BoolText(Value: Boolean): String;
begin
  if Value then
    Result := 'true'
  else
    Result := 'false';
end;

function ReadManifestBoolean(
  Section: String;
  Key: String;
  var Value: Boolean): Boolean;
var
  Text: String;
begin
  Text := GetIniString(Section, Key, '!', ManifestPath());
  Result := (Text = 'true') or (Text = 'false');
  if Result then
    Value := Text = 'true';
end;

function IsLowerHexHashOrEmpty(Value: String): Boolean;
var
  Index: Integer;
begin
  if Value = '' then
  begin
    Result := True;
    exit;
  end;
  Result := Length(Value) = 64;
  if not Result then
    exit;
  for Index := 1 to Length(Value) do
    if Pos(Value[Index], '0123456789abcdef') = 0 then
    begin
      Result := False;
      exit;
    end;
end;

function CanonicalRoot(Path: String): String;
begin
  Result := RemoveBackslashUnlessRoot(ExpandFileName(Path));
end;

function ValidateExistingManifest(
  Root: String;
  var Exists: Boolean;
  var FailureReason: String): Boolean;
var
  Index: Integer;
  Section: String;
  CreatedValue: Boolean;
  ExistedValue: Boolean;
  SharedValue: Boolean;
  RemoveValue: Boolean;
  OriginalHash: String;
begin
  FailureReason := '';
  Exists := FileExists(ManifestPath());
  if not Exists then
  begin
    Result := True;
    exit;
  end;

  Result := False;
  if GetIniString('Metadata', 'SchemaVersion', '', ManifestPath()) <> '1' then
    FailureReason := 'unsupported or missing SchemaVersion'
  else if GetIniString('Metadata', 'InstalledVersion', '', ManifestPath()) <>
    '{#AppVersion}' then
    FailureReason := 'InstalledVersion does not match the compiled installer'
  else if GetIniString('Metadata', 'FileCount', '', ManifestPath()) <>
    IntToStr(CompiledPayloadCount) then
    FailureReason := 'FileCount does not match the compiled payload count'
  else if GetIniString('Metadata', 'Complete', '', ManifestPath()) <> 'true' then
    FailureReason := 'Complete is missing or is not exactly true'
  else if CompareText(
    CanonicalRoot(GetIniString('Metadata', 'ObsRoot', '', ManifestPath())),
    CanonicalRoot(Root)) <> 0 then
    FailureReason := 'recorded OBS root differs from the uninstall root';
  if FailureReason <> '' then
    exit;

  for Index := 0 to CompiledPayloadCount - 1 do
  begin
    Section := 'File.' + IntToStr(Index);
    if GetIniString(Section, 'Id', '', ManifestPath()) <> PayloadId(Index) then
      FailureReason := Section + ' has a missing, swapped, or unexpected payload ID'
    else if GetIniString(Section, 'RelativePath', '', ManifestPath()) <>
      PayloadRelativePath(Index) then
      FailureReason := Section + ' path differs from the compiled allowlist'
    else if GetIniString(Section, 'InstalledVersion', '', ManifestPath()) <>
      '{#AppVersion}' then
      FailureReason := Section + ' installed version is invalid'
    else if GetIniString(Section, 'InstalledSHA256', '', ManifestPath()) <>
      PayloadInstalledHash(Index) then
      FailureReason := Section + ' hash differs from the compiled payload hash'
    else if not ReadManifestBoolean(
      Section, 'CreatedByInstaller', CreatedValue) then
      FailureReason := Section + ' CreatedByInstaller is not a valid Boolean'
    else if not ReadManifestBoolean(Section, 'ExistedBefore', ExistedValue) then
      FailureReason := Section + ' ExistedBefore is not a valid Boolean'
    else if not ReadManifestBoolean(Section, 'Shared', SharedValue) then
      FailureReason := Section + ' Shared is not a valid Boolean'
    else if SharedValue <> PayloadShared(Index) then
      FailureReason := Section + ' shared classification differs from compiled policy'
    else if not ReadManifestBoolean(
      Section, 'RemoveOnUninstall', RemoveValue) then
      FailureReason := Section + ' RemoveOnUninstall is not a valid Boolean'
    else if RemoveValue <> PayloadRemoveOnUninstall(Index) then
      FailureReason := Section + ' removal classification differs from compiled policy';
    if FailureReason <> '' then
      exit;
    OriginalHash := GetIniString(Section, 'OriginalSHA256', '!', ManifestPath());
    if not IsLowerHexHashOrEmpty(OriginalHash) then
    begin
      FailureReason := Section + ' OriginalSHA256 is malformed';
      exit;
    end;
  end;
  Result := True;
end;

function PreflightPayload(Root: String; ManifestExists: Boolean): String;
var
  Index: Integer;
  Section: String;
  TargetPath: String;
  CurrentHash: String;
  BooleanValue: Boolean;
begin
  Result := '';
  for Index := 0 to CompiledPayloadCount - 1 do
  begin
    TargetPath := AddBackslash(Root) + PayloadRelativePath(Index);
    PayloadWillCopy[Index] := True;
    PayloadExistedBefore[Index] := False;
    PayloadOriginalHash[Index] := '';
    PayloadCreatedByInstaller[Index] := True;

    if FileExists(TargetPath) then
    begin
      CurrentHash := Lowercase(GetSHA256OfFile(TargetPath));
      if ManifestExists then
      begin
        if CompareText(CurrentHash, PayloadInstalledHash(Index)) <> 0 then
        begin
          Result :=
            'An installer-owned OBS Auto Framing file was modified:' + #13#10 +
            PayloadRelativePath(Index) + #13#10 + #13#10 +
            'For safety, setup will not change any payload files.';
          exit;
        end;
        Section := 'File.' + IntToStr(Index);
        ReadManifestBoolean(Section, 'CreatedByInstaller', BooleanValue);
        PayloadCreatedByInstaller[Index] := BooleanValue;
        ReadManifestBoolean(Section, 'ExistedBefore', BooleanValue);
        PayloadExistedBefore[Index] := BooleanValue;
        PayloadOriginalHash[Index] :=
          GetIniString(Section, 'OriginalSHA256', '', ManifestPath());
        PayloadWillCopy[Index] := False;
      end
      else if PayloadRecognizesManualHash(Index, CurrentHash) then
      begin
        PayloadExistedBefore[Index] := True;
        PayloadOriginalHash[Index] := CurrentHash;
        PayloadCreatedByInstaller[Index] := not PayloadShared(Index);
        PayloadWillCopy[Index] :=
          CompareText(CurrentHash, PayloadInstalledHash(Index)) <> 0;
      end
      else
      begin
        Result :=
          'An unknown or modified file already exists:' + #13#10 +
          PayloadRelativePath(Index) + #13#10 + #13#10 +
          'For safety, setup will not replace it or change any payload files.';
        exit;
      end;
    end;
  end;
end;

function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  CheckFailed: Boolean;
  ManifestExists: Boolean;
  ManifestFailureReason: String;
begin
  Result := '';
  if QueryObsRunning(CheckFailed) then
  begin
    if CheckFailed then
      Result := 'Setup could not safely determine whether OBS Studio is running. Close OBS and verify Windows PowerShell process queries, then try again.'
    else
      Result := 'OBS Studio is running. Close OBS before installing, upgrading, or repairing OBS Auto Framing.';
    exit;
  end;
  if not ObsRootIsValid(WizardDirValue()) then
  begin
    Result := 'Invalid OBS root. Select the folder that contains bin\64bit\obs64.exe.';
    exit;
  end;
  if not ValidateExistingManifest(
    WizardDirValue(), ManifestExists, ManifestFailureReason) then
  begin
    Result :=
      'The existing OBS Auto Framing ownership manifest is incomplete or invalid.' +
      '' + #13#10 + #13#10 +
      ManifestFailureReason + #13#10 + #13#10 +
      'For safety, setup will not change any payload files. Review the setup log or use a separate OBS root.';
    exit;
  end;
  Result := PreflightPayload(WizardDirValue(), ManifestExists);
end;

procedure WriteManifestRecord(Index: Integer);
var
  Section: String;
begin
  Section := 'File.' + IntToStr(Index);
  SetIniString(Section, 'Id', PayloadId(Index), ManifestPath());
  SetIniString(Section, 'RelativePath', PayloadRelativePath(Index), ManifestPath());
  SetIniString(Section, 'InstalledVersion', '{#AppVersion}', ManifestPath());
  SetIniString(Section, 'InstalledSHA256', PayloadInstalledHash(Index), ManifestPath());
  SetIniString(Section, 'CreatedByInstaller',
    BoolText(PayloadCreatedByInstaller[Index]), ManifestPath());
  SetIniString(Section, 'ExistedBefore',
    BoolText(PayloadExistedBefore[Index]), ManifestPath());
  SetIniString(Section, 'OriginalSHA256', PayloadOriginalHash[Index], ManifestPath());
  SetIniString(Section, 'Shared', BoolText(PayloadShared(Index)), ManifestPath());
  SetIniString(Section, 'RemoveOnUninstall',
    BoolText(PayloadRemoveOnUninstall(Index)), ManifestPath());
end;

procedure WriteOwnershipManifest();
var
  Index: Integer;
begin
  ForceDirectories(ExtractFileDir(ManifestPath()));
  SetIniString('Metadata', 'SchemaVersion', '1', ManifestPath());
  SetIniString('Metadata', 'InstalledVersion', '{#AppVersion}', ManifestPath());
  SetIniString('Metadata', 'ObsRoot', CanonicalRoot(WizardDirValue()), ManifestPath());
  SetIniString('Metadata', 'FileCount', IntToStr(CompiledPayloadCount), ManifestPath());
  SetIniString('Metadata', 'Complete', 'false', ManifestPath());
  for Index := 0 to CompiledPayloadCount - 1 do
    WriteManifestRecord(Index);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssInstall then
    WriteOwnershipManifest()
  else if CurStep = ssPostInstall then
    SetIniString('Metadata', 'Complete', 'true', ManifestPath());
end;

procedure RemoveOwnedFile(Index: Integer; Root: String);
var
  Section: String;
  FullPath: String;
  CurrentHash: String;
  CreatedByInstaller: Boolean;
begin
  Section := 'File.' + IntToStr(Index);
  FullPath := AddBackslash(Root) + PayloadRelativePath(Index);
  if not FileExists(FullPath) then
  begin
    Log('Installer payload already absent: ' + FullPath);
    exit;
  end;
  CurrentHash := Lowercase(GetSHA256OfFile(FullPath));
  if CompareText(CurrentHash, PayloadInstalledHash(Index)) <> 0 then
  begin
    Log('Preserved installer payload modified after installation: ' + FullPath);
    exit;
  end;
  ReadManifestBoolean(Section, 'CreatedByInstaller', CreatedByInstaller);
  if not CreatedByInstaller then
  begin
    Log('Preserved pre-existing payload: ' + FullPath);
    exit;
  end;
  if not PayloadRemoveOnUninstall(Index) then
  begin
    Log('Preserved payload classified as non-removable: ' + FullPath);
    exit;
  end;
  if DeleteFile(FullPath) then
    Log('Removed installer-owned file: ' + FullPath)
  else
    Log('Could not remove installer-owned file: ' + FullPath);
end;

procedure RemoveEmptyPluginDirectories(Root: String);
var
  PluginDataRoot: String;
begin
  PluginDataRoot := AddBackslash(Root) + 'data\obs-plugins\{#PluginName}';
  RemoveDir(PluginDataRoot + '\docs');
  RemoveDir(PluginDataRoot + '\models');
  RemoveDir(PluginDataRoot + '\locale');
  RemoveDir(PluginDataRoot + '\effects');
  RemoveDir(PluginDataRoot + '\installer');
  RemoveDir(PluginDataRoot);
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  Index: Integer;
  Root: String;
  ManifestExists: Boolean;
  ManifestFailureReason: String;
begin
  if CurUninstallStep <> usUninstall then
    exit;

  Root := ExpandConstant('{app}');
  if not ObsRootIsValid(Root) then
  begin
    Log('Preserved all payload files because the recorded root is no longer a valid OBS root: ' + Root);
    exit;
  end;
  if not ValidateExistingManifest(
    Root, ManifestExists, ManifestFailureReason) or not ManifestExists then
  begin
    if not ManifestExists then
      ManifestFailureReason := 'ownership manifest is missing';
    Log('Preserved all payload files: ' + ManifestFailureReason + '.');
    exit;
  end;
  for Index := 0 to CompiledPayloadCount - 1 do
    RemoveOwnedFile(Index, Root);
  DeleteFile(ManifestPath());
  RemoveEmptyPluginDirectories(Root);
end;
